### ISSUE TITLE
Incorrect Perkins Stop

### ISSUE THREAD

**Issue by corbanmailloux** [ahollenbach/RITNextBus#1]
It seems that the Perkins times come from the second Perkins stop, according to [the schedule](http://www.rit.edu/fa/facilities/sites/rit.edu.fa.facilities/files/docs/busschedules/39614_RIT_ParkPt%20Perkins.pdf).

That stop is actually the stop near Park Point. If the first listed times were used, it would be the Perkins stop.

**Comment by corbanmailloux** [comment]
This bus system is no longer running, so I'm closing my issue.

**Comment by ahollenbach** [comment]
Thanks for creating the issue. Unfortunately, I've been a bit of an absent developer, but now have some time to migrate to the new bus system/API, so changes will be coming up soon. Really sorry about that and never merging in your PR :frowning:

**Comment by corbanmailloux** [comment]
No problem at all. :)
